/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "keyboard_out_aliases.h"
#include "keyboard_out.h"
#include "keyboard_in_aliases.h"
#include "keyboard_in.h"
#include "timer_clock.h"
#include "timer_debouncer.h"
#include "int_debouncer.h"
#include "PC.h"
#include "Led_aliases.h"
#include "Led.h"
#include "timer_puertaAbierta.h"
#include "int_puertaAbierta.h"
#include "Clock_1.h"
#include "SensorPuerta_aliases.h"
#include "SensorPuerta.h"
#include "int_sensorON.h"
#include "int_sensorOFF.h"
#include "PC_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

